apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replica set labels
  labels: 
    {{ include "common.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # these labels are used to select pods
    matchLabels: 
      {{ include "common.labels" . | indent 6 }}
  # pod definition
  template:
    metadata:
      labels: 
        {{ include "common.labels" . | indent 8 }}
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}